#!/usr/bin/env bash
# Vault Health Audit — runs all checks in parallel, generates report + CSV, fixes frontmatter.
# Usage: ./vault-audit.sh [--no-fix] [--date YYYY-MM-DD]
#
# Options:
#   --no-fix     Run audit only, skip frontmatter fix
#   --date DATE  Use custom date for output filenames (default: today)

set -euo pipefail

VAULT="/Users/S.Parodi/Library/Mobile Documents/com~apple~CloudDocs/Obsidian/Vault"
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTDIR="$VAULT/99 System"
DATE="${DATE:-$(date +%Y-%m-%d)}"
NO_FIX=0

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-fix) NO_FIX=1; shift ;;
        --date)   DATE="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

echo "=== Vault Health Audit: $DATE ==="
echo "Vault: $VAULT"
echo ""

# Run three checks in parallel
echo "Running checks in parallel..."
python3 "$SCRIPTS_DIR/audit_frontmatter.py" > "$TMP/frontmatter.json" &
PID1=$!
python3 "$SCRIPTS_DIR/audit_wikilinks.py"   > "$TMP/wikilinks.json"   &
PID2=$!
python3 "$SCRIPTS_DIR/audit_orphans.py"     > "$TMP/orphans.json"     &
PID3=$!

wait $PID1 && echo "  [1/3] Frontmatter check done" || { echo "  [1/3] Frontmatter check FAILED"; exit 1; }
wait $PID2 && echo "  [2/3] Wikilink check done"    || { echo "  [2/3] Wikilink check FAILED"; exit 1; }
wait $PID3 && echo "  [3/3] Orphan check done"      || { echo "  [3/3] Orphan check FAILED"; exit 1; }

echo ""

# Generate report + CSV via Python
python3 - <<PYEOF
import json, csv, os
from collections import Counter

VAULT   = "$VAULT"
DATE    = "$DATE"
OUTDIR  = "$OUTDIR"
TMPDIR  = "$TMP"
IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.bmp'}

fm = json.load(open(f"{TMPDIR}/frontmatter.json"))
wl = json.load(open(f"{TMPDIR}/wikilinks.json"))
or_ = json.load(open(f"{TMPDIR}/orphans.json"))

img_broken  = [x for x in wl if os.path.splitext(x['link'])[1].lower() in IMAGE_EXTS]
note_broken = [x for x in wl if os.path.splitext(x['link'])[1].lower() not in IMAGE_EXTS]

no_fm      = [f for f in fm if not f['has_frontmatter']]
miss_title   = [f for f in fm if 'title'   in f['missing']]
miss_type    = [f for f in fm if 'type'    in f['missing']]
miss_created = [f for f in fm if 'created' in f['missing']]
miss_tags    = [f for f in fm if 'tags'    in f['missing']]

total_files = sum(
    1 for r, dirs, files in os.walk(VAULT)
    for f in files if f.endswith('.md')
    if not any(p.startswith('.') for p in r.replace(VAULT,'').split(os.sep))
)

fm_by_folder = Counter(f['file'].split('/')[0] if '/' in f['file'] else 'root' for f in fm)
or_by_folder = Counter(f['file'].split('/')[0] if '/' in f['file'] else 'root' for f in or_)

# CSV
csv_path = f"{OUTDIR}/vault-audit-{DATE}.csv"
with open(csv_path, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['check', 'file', 'detail'])
    for item in fm:
        w.writerow(['frontmatter', item['file'], 'missing: ' + ', '.join(item['missing'])])
    for item in note_broken:
        w.writerow(['broken_wikilink', item['file'], 'target: ' + item['link']])
    for item in img_broken:
        w.writerow(['broken_image_ref', item['file'], 'target: ' + item['link']])
    for item in or_:
        w.writerow(['orphan', item['file'], 'inbound_links: 0'])

top_broken = Counter(x['link'] for x in note_broken).most_common(15)
broken_by_file = Counter(x['file'] for x in note_broken).most_common(15)

def folder_table(counter):
    rows = ''
    for folder, count in sorted(counter.items(), key=lambda x: -x[1]):
        rows += f'| \`{folder}\` | {count} |\n'
    return rows

report = f"""---
type: note
topic: meta
created: {DATE}
tags:
  - audit
  - vault-health
title: Vault Health Audit {DATE}
---

# Vault Health Audit — {DATE}

> Generated by \`vault-audit.sh\`. Source: \`99 System/vault-audit-{DATE}.csv\`

## Summary

| Check | Count |
|-------|-------|
| Total markdown files scanned | {total_files} |
| Files with frontmatter issues | {len(fm)} |
| Broken wikilinks (notes) | {len(note_broken)} |
| Broken image references | {len(img_broken)} |
| Orphan notes (0 inbound links) | {len(or_)} |
| **Total issues** | **{len(fm) + len(wl) + len(or_)}** |

---

## 1. Frontmatter Issues

**{len(fm)} files** have missing required fields (\`title\`, \`created\`, \`tags\`, \`type\`).

| Issue | Count |
|-------|-------|
| No frontmatter at all | {len(no_fm)} |
| Missing \`title\` | {len(miss_title)} |
| Missing \`type\` | {len(miss_type)} |
| Missing \`created\` | {len(miss_created)} |
| Missing \`tags\` | {len(miss_tags)} |

### By folder

| Folder | Files |
|--------|-------|
{folder_table(fm_by_folder)}
---

## 2. Broken Wikilinks

**{len(note_broken)} broken note links** across **{len(set(x['file'] for x in note_broken))} files**.
**{len(img_broken)} broken image references**.

### Top broken targets

| Target | Refs |
|--------|------|
""" + ''.join(f'| `{t}` | {c} |\n' for t, c in top_broken) + f"""
### Files with most broken links

| File | Count |
|------|-------|
""" + ''.join(f'| `{f}` | {c} |\n' for f, c in broken_by_file) + f"""
---

## 3. Orphan Notes

**{len(or_)} notes** with zero inbound links.

### By folder

| Folder | Orphans |
|--------|---------|
{folder_table(or_by_folder)}
---

## 4. Frontmatter Fixes

See section below — fix was {"applied" if "$NO_FIX" == "0" else "skipped (--no-fix)"}.
"""

md_path = f"{OUTDIR}/vault-audit-{DATE}.md"
with open(md_path, 'w', encoding='utf-8') as f:
    f.write(report)

print(f"Report: {md_path}")
print(f"CSV:    {csv_path} ({len(fm) + len(wl) + len(or_)} rows)")
PYEOF

# Fix frontmatter (unless --no-fix)
if [[ $NO_FIX -eq 0 ]]; then
    echo ""
    echo "Fixing missing frontmatter..."
    python3 "$SCRIPTS_DIR/fix_frontmatter.py" "$TMP/frontmatter.json"
else
    echo "(--no-fix: skipping frontmatter fix)"
fi

echo ""
echo "Done."
